In [1]:
# Read all UCLA datasets.
# There are 5 different datasets.

import csv
import pandas as pd

In [ ]:
# 1. 'usage_bld_kwh.csv' ([geo_id', 'sqft', 'usage', 'usage_med', 'usage_med_sqft', 'usetype', 'year', 'name', 'solar_potential', 'pop', 'usage_percap', 'source'], dtype='object

# 2. 'usage_vintage_kwh.csv' (['geo_id', 'sqft', 'usage', 'usage_med', 'usage_med_sqft', 'usetype', 'vintage_id', 'year', 'name', 'source'], dtype='object')

# 3. 'usage_income_kwh.csv' (['geo_id', 'year', 'income_quintile', 'income_range', 'usage', 'pop', 'usetype', 'usage_percap', 'name', 'source'], dtype='object')

# 4. 'usage_sqft_kwh.csv' (['geo_id', 'sqft', 'sqft_id', 'usage', 'usage_med', 'usage_med_sqft', 'usetype', 'year', 'name', 'source'], dtype='object')

# 5. 'geos.csv' (['geo_id', 'name', 'pop', 'pop_sqmi', 'med_income', 'pct_own', 'pct_rent', 'year', 'enviroscreen_tracts', 'sqmi', 'solar_pot', 'net_solar_pot', 'count', 'source'], dtype='object')

In [2]:
# Dataset 1: Consumption Information by Parcel Use-Type
import pandas as pd

df1 = pd.read_csv('usage_bld_kwh.csv')
df1["source"] = "usage_bld_kwh"
print(df1.columns)

Index(['geo_id', 'sqft', 'usage', 'usage_med', 'usage_med_sqft', 'usetype',
       'year', 'name', 'solar_potential', 'pop', 'usage_percap', 'source'],
      dtype='object')

In [3]:
# Dataset 2: Consumption Information by Building Vintage
import pandas as pd

df2 = pd.read_csv('usage_vintage_kwh.csv')
df2["source"] = "usage_vintage_kwh"
print(df2.columns)

Index(['geo_id', 'sqft', 'usage', 'usage_med', 'usage_med_sqft', 'usetype',
       'vintage_id', 'year', 'name', 'source'],
      dtype='object')

In [7]:
# Dataset 3: Consumption Information by Income Quintile for Residential Accounts 
import pandas as pd

df3 = pd.read_csv('usage_income_kwh.csv')
df3["source"] = "usage_income_kwh"
print(df3.columns)

Index(['geo_id', 'year', 'income_quintile', 'income_range', 'usage', 'pop',
       'usetype', 'usage_percap', 'name', 'source'],
      dtype='object')

In [9]:
# Dataset 4: Consumption information by Square Footage Intervals
import pandas as pd

df4 = pd.read_csv('usage_sqft_kwh.csv')
df4["source"] = "usage_sqft_kwh"
print(df4.columns)

Index(['geo_id', 'sqft', 'sqft_id', 'usage', 'usage_med', 'usage_med_sqft',
       'usetype', 'year', 'name', 'source'],
      dtype='object')

In [11]:
# Dataset 5: Socioeconomic and Solar Information (Add this to the Metadata Word file)
import pandas as pd

df5 = pd.read_csv('geos.csv')
df5["source"] = "geos"
print(df5.columns)

Index(['geo_id', 'name', 'pop', 'pop_sqmi', 'med_income', 'pct_own',
       'pct_rent', 'year', 'enviroscreen_tracts', 'sqmi', 'solar_pot',
       'net_solar_pot', 'count', 'source'],
      dtype='object')

In [13]:
# Merging the Datasets and displaying it

import pandas as pd

df_merged = pd.concat([df1, df2, df3, df4, df5], join='outer').fillna('NA')
# Currently I am doing an outer merge, but I need to double check if I am creating redundancy with
# doing an outer merge. Consider what would happen if we do inner join.

print('The Columns:',df_merged.columns,'\n','-'*100,'\n')
display(df_merged)
ucla_merged = df_merged.copy()

place_names =(ucla_merged['name'].unique()) 
# To see the unique places printed
#for place in place_names:
    #print(place)
#ucla_merged.to_csv('ucla_merged.csv')

The Columns: Index(['geo_id', 'sqft', 'usage', 'usage_med', 'usage_med_sqft', 'usetype',
       'year', 'name', 'solar_potential', 'pop', 'usage_percap', 'source',
       'vintage_id', 'income_quintile', 'income_range', 'sqft_id', 'pop_sqmi',
       'med_income', 'pct_own', 'pct_rent', 'enviroscreen_tracts', 'sqmi',
       'solar_pot', 'net_solar_pot', 'count'],
      dtype='object')
 ----------------------------------------------------------------------------------------------------

,geo_id,sqft,usage,usage_med,usage_med_sqft,usetype,year,name,solar_potential,pop,...,sqft_id,pop_sqmi,med_income,pct_own,pct_rent,enviroscreen_tracts,sqmi,solar_pot,net_solar_pot,count
0,cities_1,1253.0,masked,masked,masked,agriculture,2016,agoura hills,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
1,cities_1,4802115.0,65825608.0000,121901,9.7676,commercial,2016,agoura hills,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
2,cities_1,8906397.0,43707916.6000,9136,3.9839,condo,2016,agoura hills,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
3,cities_1,734698.0,masked,masked,masked,industrial,2016,agoura hills,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
4,cities_1,100192.0,masked,masked,masked,institutional,2016,agoura hills,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
957,cities_4,NA,NA,NA,NA,NA,2010,azusa,NA,45301.0,...,NA,3204.573593,59007.0,0.567021,0.432654,4.0,14.136358,255537607.5,-8888.0,-9999.0
958,cities_173,NA,NA,NA,NA,NA,2010,irvine,NA,-7777.0,...,NA,-7777.0,-7777.0,-7777.0,-7777.0,0.0,95.89453,NA,-8888.0,-7777.0
959,cities_182,NA,NA,NA,NA,NA,2010,newport beach,NA,-7777.0,...,NA,-7777.0,-7777.0,-7777.0,-7777.0,0.0,37.307898,NA,-8888.0,-7777.0
960,cities_183,NA,NA,NA,NA,NA,2010,orange,NA,-7777.0,...,NA,-7777.0,-7777.0,-7777.0,-7777.0,1.0,36.512519,NA,-8888.0,-7777.0
961,cities_178,NA,NA,NA,NA,NA,2010,laguna woods,NA,-7777.0,...,NA,-7777.0,-7777.0,-7777.0,-7777.0,0.0,4.775987,NA,-8888.0,-7777.0

In [15]:
# Creating the locations dataframe with columns 'geo_id' and 'name'(location)

location_keys = ucla_merged[['geo_id', 'name']].drop_duplicates().reset_index(drop=True)
#display(location_keys)

# Preparing the Format of Location for Geocoding API
    # Adding ', CA' next to the values of 'name'.
import pandas as pd
locations = location_keys.copy()
locations['query_for_api'] = locations['name'] + ', CA'
display(locations)
#locations.to_csv('locations.csv') No need to save
# Displaying and double checking locations dataframe

                geo_id                   name              query_for_api
0             cities_1           agoura hills           agoura hills, CA
1            cities_10                 carson                 carson, CA
2           cities_100              camarillo              camarillo, CA
3           cities_101               fillmore               fillmore, CA
4           cities_102               moorpark               moorpark, CA
..                 ...                    ...                        ...
477   neighborhoods_96              calabasas              calabasas, CA
478   neighborhoods_97            canoga park            canoga park, CA
479   neighborhoods_98                 carson                 carson, CA
480   neighborhoods_99                carthay                carthay, CA
481  neighborhoods_178  la caã±ada flintridge  la caã±ada flintridge, CA

[482 rows x 3 columns]

In [17]:
# Creating a function to use the Google's Geocoding API

# Structure of the API:
    # https://maps.googleapis.com/maps/api/geocode/json?address=xxx&key=xxx

import requests

def geocode_location(location_name: str, api_key):
    base_url = "https://maps.googleapis.com/maps/api/geocode/json"
    params = {
        "address": location_name,
        "key": api_key
    }
    try:
        response = requests.get(base_url, params=params)
        response.raise_for_status()
        data = response.json()
    except:
        sys.stderr.write(f'Error: The url {base_url} with address {location_name} could not be requested properly!\n')
        return {
            "query": location_name,
            "num_results": 0,
            "data": None,
            "error": "REQUEST_FAILED"
        }
    
    if data['status'] == 'OK':
        len_of_results = len(data['results'])
        result = data['results'][0]
        components = result['address_components']
        print('Data successfully requested.')
        return {"query": location_name, 
                'num_results':len_of_results,
                'data':data
        }
        
    else:
        print(f" Google API error: {data['status']} for '{location_name}'")
        return {
            "query": location_name,
            "num_results": 0,
            "data": None,
            "error": data['status']
        }

In [21]:
# Creating the 'api_results' using the API function I have created

import time

my_api_key = 'PUT YOUR API KEY HERE'
api_results = list()

for index, row in locations.iterrows():
    time.sleep(0.15)
    print(row['geo_id'], ' ', row['query_for_api'])  
    
    response = geocode_location(row['query_for_api'], my_api_key)

    # Append all relevant info
    api_results.append((row['geo_id'], 
                        row['query_for_api'], 
                        {"num_results": response.get("num_results", 0),
                        "error": response.get("error", None),
                        "data": response.get("data", None)} ))

cities_1   agoura hills, CA
Data successfully requested.
cities_10   carson, CA
Data successfully requested.
cities_100   camarillo, CA
Data successfully requested.
cities_101   fillmore, CA
Data successfully requested.
cities_102   moorpark, CA
Data successfully requested.
cities_103   ojai, CA
Data successfully requested.
cities_104   santa paula, CA
Data successfully requested.
cities_105   simi valley, CA
Data successfully requested.
cities_106   thousand oaks, CA
Data successfully requested.
cities_107   port hueneme, CA
Data successfully requested.
cities_108   oxnard, CA
Data successfully requested.
cities_109   san buenaventura, CA
Data successfully requested.
cities_11   cerritos, CA
Data successfully requested.
cities_110   adelanto, CA
Data successfully requested.
cities_111   apple valley, CA
Data successfully requested.
cities_112   barstow, CA
Data successfully requested.
cities_113   big bear lake, CA
Data successfully requested.
cities_114   chino, CA
Data successfully requested.
cities_115   chino hills, CA
Data successfully requested.
cities_116   colton, CA
Data successfully requested.
cities_117   fontana, CA
Data successfully requested.
cities_118   grand terrace, CA
Data successfully requested.
cities_119   hesperia, CA
Data successfully requested.
cities_12   claremont, CA
Data successfully requested.
cities_120   highland, CA
Data successfully requested.
cities_121   loma linda, CA
Data successfully requested.
cities_122   montclair, CA
Data successfully requested.
cities_123   needles, CA
Data successfully requested.
cities_124   ontario, CA
Data successfully requested.
cities_125   rancho cucamonga, CA
Data successfully requested.
cities_126   redlands, CA
Data successfully requested.
cities_127   rialto, CA
Data successfully requested.
cities_128   san bernardino, CA
Data successfully requested.
cities_129   twentynine palms, CA
Data successfully requested.
cities_13   commerce, CA
Data successfully requested.
cities_130   upland, CA
Data successfully requested.
cities_131   victorville, CA
Data successfully requested.
cities_132   yucaipa, CA
Data successfully requested.
cities_133   yucca valley, CA
Data successfully requested.
cities_134   banning, CA
Data successfully requested.
cities_135   beaumont, CA
Data successfully requested.
cities_136   blythe, CA
Data successfully requested.
cities_137   calimesa, CA
Data successfully requested.
cities_138   canyon lake, CA
Data successfully requested.
cities_139   cathedral city, CA
Data successfully requested.
cities_14   compton, CA
Data successfully requested.
cities_140   coachella, CA
Data successfully requested.
cities_141   corona, CA
Data successfully requested.
cities_142   desert hot springs, CA
Data successfully requested.
cities_143   hemet, CA
Data successfully requested.
cities_144   indian wells, CA
Data successfully requested.
cities_145   indio, CA
Data successfully requested.
cities_146   la quinta, CA
Data successfully requested.
cities_147   lake elsinore, CA
Data successfully requested.
cities_148   menifee, CA
Data successfully requested.
cities_149   moreno valley, CA
Data successfully requested.
cities_15   covina, CA
Data successfully requested.
cities_150   murrieta, CA
Data successfully requested.
cities_151   norco, CA
Data successfully requested.
cities_152   palm desert, CA
Data successfully requested.
cities_153   palm springs, CA
Data successfully requested.
cities_154   perris, CA
Data successfully requested.
cities_155   rancho mirage, CA
Data successfully requested.
cities_156   riverside, CA
Data successfully requested.
cities_157   san jacinto, CA
Data successfully requested.
cities_158   temecula, CA
Data successfully requested.
cities_159   wildomar, CA
Data successfully requested.
cities_16   el segundo, CA
Data successfully requested.
cities_160   jurupa valley, CA
Data successfully requested.
cities_161   eastvale, CA
Data successfully requested.
cities_162   aliso viejo, CA
Data successfully requested.
cities_163   anaheim, CA
Data successfully requested.
cities_164   brea, CA
Data successfully requested.
cities_165   buena park, CA
Data successfully requested.
cities_166   costa mesa, CA
Data successfully requested.
cities_167   cypress, CA
Data successfully requested.
cities_168   dana point, CA
Data successfully requested.
cities_169   fountain valley, CA
Data successfully requested.
cities_17   whittier, CA
Data successfully requested.
cities_170   fullerton, CA
Data successfully requested.
cities_171   garden grove, CA
Data successfully requested.
cities_172   huntington beach, CA
Data successfully requested.
cities_173   irvine, CA
Data successfully requested.
cities_174   la habra, CA
Data successfully requested.
cities_175   laguna beach, CA
Data successfully requested.
cities_176   laguna hills, CA
Data successfully requested.
cities_177   laguna niguel, CA
Data successfully requested.
cities_178   laguna woods, CA
Data successfully requested.
cities_179   lake forest, CA
Data successfully requested.
cities_18   glendale, CA
Data successfully requested.
cities_180   los alamitos, CA
Data successfully requested.
cities_181   mission viejo, CA
Data successfully requested.
cities_182   newport beach, CA
Data successfully requested.
cities_183   orange, CA
Data successfully requested.
cities_184   placentia, CA
Data successfully requested.
cities_185   rancho santa margarita, CA
Data successfully requested.
cities_186   san clemente, CA
Data successfully requested.
cities_187   san juan capistrano, CA
Data successfully requested.
cities_188   santa ana, CA
Data successfully requested.
cities_189   seal beach, CA
Data successfully requested.
cities_19   glendora, CA
Data successfully requested.
cities_190   stanton, CA
Data successfully requested.
cities_191   tustin, CA
Data successfully requested.
cities_192   villa park, CA
Data successfully requested.
cities_193   westminster, CA
Data successfully requested.
cities_194   yorba linda, CA
Data successfully requested.
cities_195   westmorland, CA
Data successfully requested.
cities_196   el centro, CA
Data successfully requested.
cities_197   imperial, CA
Data successfully requested.
cities_198   holtville, CA
Data successfully requested.
cities_199   calipatria, CA
Data successfully requested.
cities_2   alhambra, CA
Data successfully requested.
cities_20   huntington park, CA
Data successfully requested.
cities_200   brawley, CA
Data successfully requested.
cities_201   calexico, CA
Data successfully requested.
cities_202   ventura unincorporated area, CA
Data successfully requested.
cities_203   san bernardino unincorporated area, CA
Data successfully requested.
cities_204   riverside unincorporated area, CA
Data successfully requested.
cities_205   orange unincorporated area, CA
Data successfully requested.
cities_206   imperial unincorporated area, CA
Data successfully requested.
cities_21   industry, CA
Data successfully requested.
cities_22   la puente, CA
Data successfully requested.
cities_23   lancaster, CA
Data successfully requested.
cities_24   artesia, CA
Data successfully requested.
cities_25   avalon, CA
Data successfully requested.
cities_26   bradbury, CA
Data successfully requested.
cities_27   burbank, CA
Data successfully requested.
cities_28   calabasas, CA
Data successfully requested.
cities_29   cudahy, CA
Data successfully requested.
cities_3   arcadia, CA
Data successfully requested.
cities_30   culver city, CA
Data successfully requested.
cities_31   diamond bar, CA
Data successfully requested.
cities_32   downey, CA
Data successfully requested.
cities_33   duarte, CA
Data successfully requested.
cities_34   el monte, CA
Data successfully requested.
cities_342   la palma, CA
Data successfully requested.
cities_343   los angeles unincorporated area, CA
Data successfully requested.
cities_35   gardena, CA
Data successfully requested.
cities_36   inglewood, CA
Data successfully requested.
cities_37   irwindale, CA
Data successfully requested.
cities_38   la canada flintridge, CA
Data successfully requested.
cities_39   la habra heights, CA
Data successfully requested.
cities_4   azusa, CA
Data successfully requested.
cities_40   hawaiian gardens, CA
Data successfully requested.
cities_41   hawthorne, CA
Data successfully requested.
cities_42   palmdale, CA
Data successfully requested.
cities_43   palos verdes estates, CA
Data successfully requested.
cities_44   paramount, CA
Data successfully requested.
cities_45   pasadena, CA
Data successfully requested.
cities_46   pico rivera, CA
Data successfully requested.
cities_47   pomona, CA
Data successfully requested.
cities_48   rancho palos verdes, CA
Data successfully requested.
cities_49   redondo beach, CA
Data successfully requested.
cities_5   baldwin park, CA
Data successfully requested.
cities_50   rolling hills, CA
Data successfully requested.
cities_51   hermosa beach, CA
Data successfully requested.
cities_52   hidden hills, CA
Data successfully requested.
cities_53   la mirada, CA
Data successfully requested.
cities_54   la verne, CA
Data successfully requested.
cities_55   lakewood, CA
Data successfully requested.
cities_56   rolling hills estates, CA
Data successfully requested.
cities_57   rosemead, CA
Data successfully requested.
cities_58   san dimas, CA
Data successfully requested.
cities_59   san fernando, CA
Data successfully requested.
cities_6   bell, CA
 Google API error: ZERO_RESULTS for 'bell, CA'
cities_60   san gabriel, CA
Data successfully requested.
cities_61   san marino, CA
Data successfully requested.
cities_62   santa clarita, CA
Data successfully requested.
cities_63   santa fe springs, CA
Data successfully requested.
cities_64   santa monica, CA
Data successfully requested.
cities_65   lawndale, CA
Data successfully requested.
cities_66   lomita, CA
Data successfully requested.
cities_67   long beach, CA
Data successfully requested.
cities_68   los angeles, CA
Data successfully requested.
cities_69   lynwood, CA
Data successfully requested.
cities_7   bell gardens, CA
Data successfully requested.
cities_70   malibu, CA
Data successfully requested.
cities_71   manhattan beach, CA
Data successfully requested.
cities_72   south pasadena, CA
Data successfully requested.
cities_73   temple city, CA
Data successfully requested.
cities_74   torrance, CA
Data successfully requested.
cities_75   vernon, CA
Data successfully requested.
cities_76   walnut, CA
Data successfully requested.
cities_77   west covina, CA
Data successfully requested.
cities_78   west hollywood, CA
Data successfully requested.
cities_79   westlake village, CA
Data successfully requested.
cities_8   bellflower, CA
Data successfully requested.
cities_80   maywood, CA
Data successfully requested.
cities_81   monrovia, CA
Data successfully requested.
cities_82   montebello, CA
Data successfully requested.
cities_83   monterey park, CA
Data successfully requested.
cities_84   norwalk, CA
Data successfully requested.
cities_85   sierra madre, CA
Data successfully requested.
cities_86   signal hill, CA
Data successfully requested.
cities_87   south el monte, CA
Data successfully requested.
cities_88   south gate, CA
Data successfully requested.
cities_9   beverly hills, CA
Data successfully requested.
cogs_1   South Bay Cities COG, CA
Data successfully requested.
cogs_2   Gateway Cities COG, CA
Data successfully requested.
cogs_3   Las Virgenes-Malibu COG, CA
Data successfully requested.
cogs_4   San Fernando Valley COG, CA
Data successfully requested.
cogs_5   Westside Cities COG, CA
Data successfully requested.
cogs_6   San Gabriel Valley COG, CA
Data successfully requested.
counties_13   Imperial County, CA
Data successfully requested.
counties_19   Los Angeles County, CA
Data successfully requested.
counties_30   Orange County, CA
Data successfully requested.
counties_33   Riverside County, CA
Data successfully requested.
counties_36   San Bernardino County, CA
Data successfully requested.
counties_56   Ventura County, CA
Data successfully requested.
neighborhoods_100   castaic, CA
Data successfully requested.
neighborhoods_101   castaic canyons, CA
Data successfully requested.
neighborhoods_102   central-alameda, CA
Data successfully requested.
neighborhoods_103   century city, CA
Data successfully requested.
neighborhoods_104   cerritos, CA
Data successfully requested.
neighborhoods_105   charter oak, CA
Data successfully requested.
neighborhoods_106   chatsworth, CA
Data successfully requested.
neighborhoods_107   chatsworth reservoir, CA
Data successfully requested.
neighborhoods_108   chesterfield square, CA
Data successfully requested.
neighborhoods_109   cheviot hills, CA
Data successfully requested.
neighborhoods_110   chinatown, CA
Data successfully requested.
neighborhoods_111   citrus, CA
Data successfully requested.
neighborhoods_112   claremont, CA
Data successfully requested.
neighborhoods_113   commerce, CA
Data successfully requested.
neighborhoods_114   compton, CA
Data successfully requested.
neighborhoods_115   covina, CA
Data successfully requested.
neighborhoods_116   cudahy, CA
Data successfully requested.
neighborhoods_117   culver city, CA
Data successfully requested.
neighborhoods_118   cypress park, CA
Data successfully requested.
neighborhoods_119   del aire, CA
Data successfully requested.
neighborhoods_120   del rey, CA
Data successfully requested.
neighborhoods_121   desert view highlands, CA
Data successfully requested.
neighborhoods_122   diamond bar, CA
Data successfully requested.
neighborhoods_123   downey, CA
Data successfully requested.
neighborhoods_124   downtown, CA
Data successfully requested.
neighborhoods_125   duarte, CA
Data successfully requested.
neighborhoods_126   eagle rock, CA
Data successfully requested.
neighborhoods_127   east compton, CA
Data successfully requested.
neighborhoods_128   east hollywood, CA
Data successfully requested.
neighborhoods_129   east la mirada, CA
Data successfully requested.
neighborhoods_130   east los angeles, CA
Data successfully requested.
neighborhoods_131   east pasadena, CA
Data successfully requested.
neighborhoods_132   east san gabriel, CA
Data successfully requested.
neighborhoods_133   echo park, CA
Data successfully requested.
neighborhoods_134   elizabeth lake, CA
Data successfully requested.
neighborhoods_135   el monte, CA
Data successfully requested.
neighborhoods_136   el segundo, CA
Data successfully requested.
neighborhoods_137   el sereno, CA
Data successfully requested.
neighborhoods_138   elysian park, CA
Data successfully requested.
neighborhoods_139   elysian valley, CA
Data successfully requested.
neighborhoods_140   encino, CA
Data successfully requested.
neighborhoods_141   exposition park, CA
Data successfully requested.
neighborhoods_142   fairfax, CA
Data successfully requested.
neighborhoods_143   florence, CA
Data successfully requested.
neighborhoods_144   florence-firestone, CA
Data successfully requested.
neighborhoods_145   gardena, CA
Data successfully requested.
neighborhoods_146   glassell park, CA
Data successfully requested.
neighborhoods_147   glendale, CA
Data successfully requested.
neighborhoods_148   glendora, CA
Data successfully requested.
neighborhoods_149   gramercy park, CA
Data successfully requested.
neighborhoods_150   granada hills, CA
Data successfully requested.
neighborhoods_151   green meadows, CA
Data successfully requested.
neighborhoods_152   green valley, CA
Data successfully requested.
neighborhoods_153   griffith park, CA
Data successfully requested.
neighborhoods_154   hacienda heights, CA
Data successfully requested.
neighborhoods_155   hancock park, CA
Data successfully requested.
neighborhoods_156   hansen dam, CA
Data successfully requested.
neighborhoods_157   harbor city, CA
Data successfully requested.
neighborhoods_158   harbor gateway, CA
Data successfully requested.
neighborhoods_159   harvard heights, CA
Data successfully requested.
neighborhoods_160   harvard park, CA
Data successfully requested.
neighborhoods_161   hasley canyon, CA
Data successfully requested.
neighborhoods_162   hawaiian gardens, CA
Data successfully requested.
neighborhoods_163   hawthorne, CA
Data successfully requested.
neighborhoods_164   hermosa beach, CA
Data successfully requested.
neighborhoods_165   hidden hills, CA
Data successfully requested.
neighborhoods_166   highland park, CA
Data successfully requested.
neighborhoods_167   historic south-central, CA
Data successfully requested.
neighborhoods_168   hollywood, CA
Data successfully requested.
neighborhoods_169   hollywood hills, CA
Data successfully requested.
neighborhoods_170   hollywood hills west, CA
Data successfully requested.
neighborhoods_171   huntington park, CA
Data successfully requested.
neighborhoods_172   hyde park, CA
Data successfully requested.
neighborhoods_173   industry, CA
Data successfully requested.
neighborhoods_174   inglewood, CA
Data successfully requested.
neighborhoods_175   irwindale, CA
Data successfully requested.
neighborhoods_176   jefferson park, CA
Data successfully requested.
neighborhoods_177   koreatown, CA
Data successfully requested.
neighborhoods_178   la caÃ£Â±ada flintridge, CA
Data successfully requested.
neighborhoods_179   la crescenta-montrose, CA
Data successfully requested.
neighborhoods_180   ladera heights, CA
Data successfully requested.
neighborhoods_181   la habra heights, CA
Data successfully requested.
neighborhoods_182   lake balboa, CA
Data successfully requested.
neighborhoods_183   lake hughes, CA
Data successfully requested.
neighborhoods_184   lake los angeles, CA
Data successfully requested.
neighborhoods_185   lake view terrace, CA
Data successfully requested.
neighborhoods_186   lakewood, CA
Data successfully requested.
neighborhoods_187   la mirada, CA
Data successfully requested.
neighborhoods_188   lancaster, CA
Data successfully requested.
neighborhoods_189   la puente, CA
Data successfully requested.
neighborhoods_190   larchmont, CA
Data successfully requested.
neighborhoods_191   la verne, CA
Data successfully requested.
neighborhoods_192   lawndale, CA
Data successfully requested.
neighborhoods_193   leimert park, CA
Data successfully requested.
neighborhoods_194   lennox, CA
Data successfully requested.
neighborhoods_195   leona valley, CA
Data successfully requested.
neighborhoods_196   lincoln heights, CA
Data successfully requested.
neighborhoods_197   littlerock, CA
Data successfully requested.
neighborhoods_198   lomita, CA
Data successfully requested.
neighborhoods_199   long beach, CA
Data successfully requested.
neighborhoods_200   lopez/kagel canyons, CA
Data successfully requested.
neighborhoods_201   los feliz, CA
Data successfully requested.
neighborhoods_202   lynwood, CA
Data successfully requested.
neighborhoods_203   malibu, CA
Data successfully requested.
neighborhoods_204   manchester square, CA
Data successfully requested.
neighborhoods_205   manhattan beach, CA
Data successfully requested.
neighborhoods_206   marina del rey, CA
Data successfully requested.
neighborhoods_207   mar vista, CA
Data successfully requested.
neighborhoods_208   mayflower village, CA
Data successfully requested.
neighborhoods_209   maywood, CA
Data successfully requested.
neighborhoods_210   mid-city, CA
Data successfully requested.
neighborhoods_211   mid-wilshire, CA
Data successfully requested.
neighborhoods_212   mission hills, CA
Data successfully requested.
neighborhoods_213   monrovia, CA
Data successfully requested.
neighborhoods_214   montebello, CA
Data successfully requested.
neighborhoods_215   montecito heights, CA
Data successfully requested.
neighborhoods_216   monterey park, CA
Data successfully requested.
neighborhoods_217   mount washington, CA
Data successfully requested.
neighborhoods_218   northeast antelope valley, CA
Data successfully requested.
neighborhoods_219   north el monte, CA
Data successfully requested.
neighborhoods_220   north hills, CA
Data successfully requested.

In [23]:
# Checking out the first 10 result
for result in api_results[:10]:
    print(result,'\n')

# Turning the api-location results into a dataframe and saving it
import pandas as pd

df_geo = pd.DataFrame(api_results, columns=['geo_id', 'query', 'raw_result'])

# Saving the locations with apis as a csv.
df_geo.to_csv('api_locations.csv')

('cities_1', 'agoura hills, CA', {'num_results': 1, 'error': None, 'data': {'results': [{'address_components': [{'long_name': 'Agoura Hills', 'short_name': 'Agoura Hills', 'types': ['locality', 'political']}, {'long_name': 'Los Angeles County', 'short_name': 'Los Angeles County', 'types': ['administrative_area_level_2', 'political']}, {'long_name': 'California', 'short_name': 'CA', 'types': ['administrative_area_level_1', 'political']}, {'long_name': 'United States', 'short_name': 'US', 'types': ['country', 'political']}, {'long_name': '91301', 'short_name': '91301', 'types': ['postal_code']}], 'formatted_address': 'Agoura Hills, CA 91301, USA', 'geometry': {'bounds': {'northeast': {'lat': 34.168214, 'lng': -118.719776}, 'southwest': {'lat': 34.125329, 'lng': -118.8004199}}, 'location': {'lat': 34.1533395, 'lng': -118.7616764}, 'location_type': 'APPROXIMATE', 'viewport': {'northeast': {'lat': 34.168214, 'lng': -118.719776}, 'southwest': {'lat': 34.125329, 'lng': -118.8004199}}}, 'place_id': 'ChIJlRyqIx4h6IAR1v3fLa72Dqw', 'types': ['locality', 'political']}], 'status': 'OK'}})

('cities_10', 'carson, CA', {'num_results': 1, 'error': None, 'data': {'results': [{'address_components': [{'long_name': 'Carson', 'short_name': 'Carson', 'types': ['locality', 'political']}, {'long_name': 'Los Angeles County', 'short_name': 'Los Angeles County', 'types': ['administrative_area_level_2', 'political']}, {'long_name': 'California', 'short_name': 'CA', 'types': ['administrative_area_level_1', 'political']}, {'long_name': 'United States', 'short_name': 'US', 'types': ['country', 'political']}], 'formatted_address': 'Carson, CA, USA', 'geometry': {'bounds': {'northeast': {'lat': 33.8861879, 'lng': -118.205903}, 'southwest': {'lat': 33.792547, 'lng': -118.2888819}}, 'location': {'lat': 33.8316745, 'lng': -118.281693}, 'location_type': 'APPROXIMATE', 'viewport': {'northeast': {'lat': 33.8861879, 'lng': -118.205903}, 'southwest': {'lat': 33.792547, 'lng': -118.2888819}}}, 'place_id': 'ChIJfcS6fx7LwoARZYDiqXgXL6E', 'types': ['locality', 'political']}], 'status': 'OK'}})

('cities_100', 'camarillo, CA', {'num_results': 1, 'error': None, 'data': {'results': [{'address_components': [{'long_name': 'Camarillo', 'short_name': 'Camarillo', 'types': ['locality', 'political']}, {'long_name': 'Ventura County', 'short_name': 'Ventura County', 'types': ['administrative_area_level_2', 'political']}, {'long_name': 'California', 'short_name': 'CA', 'types': ['administrative_area_level_1', 'political']}, {'long_name': 'United States', 'short_name': 'US', 'types': ['country', 'political']}], 'formatted_address': 'Camarillo, CA, USA', 'geometry': {'bounds': {'northeast': {'lat': 34.2526011, 'lng': -118.9578339}, 'southwest': {'lat': 34.191366, 'lng': -119.109465}}, 'location': {'lat': 34.2163937, 'lng': -119.0376023}, 'location_type': 'APPROXIMATE', 'viewport': {'northeast': {'lat': 34.2526011, 'lng': -118.9578339}, 'southwest': {'lat': 34.191366, 'lng': -119.109465}}}, 'place_id': 'ChIJu5REjxA26IAR52xlig9BWW4', 'types': ['locality', 'political']}], 'status': 'OK'}})

('cities_101', 'fillmore, CA', {'num_results': 1, 'error': None, 'data': {'results': [{'address_components': [{'long_name': 'Fillmore', 'short_name': 'Fillmore', 'types': ['locality', 'political']}, {'long_name': 'Ventura County', 'short_name': 'Ventura County', 'types': ['administrative_area_level_2', 'political']}, {'long_name': 'California', 'short_name': 'CA', 'types': ['administrative_area_level_1', 'political']}, {'long_name': 'United States', 'short_name': 'US', 'types': ['country', 'political']}, {'long_name': '93015', 'short_name': '93015', 'types': ['postal_code']}], 'formatted_address': 'Fillmore, CA 93015, USA', 'geometry': {'bounds': {'northeast': {'lat': 34.4173339, 'lng': -118.889764}, 'southwest': {'lat': 34.38232, 'lng': -118.9420429}}, 'location': {'lat': 34.3991639, 'lng': -118.918154}, 'location_type': 'APPROXIMATE', 'viewport': {'northeast': {'lat': 34.4173339, 'lng': -118.889764}, 'southwest': {'lat': 34.38232, 'lng': -118.9420429}}}, 'place_id': 'ChIJ4Y_AB3vJ6YARa3-hHmvlV5o', 'types': ['locality', 'political']}], 'status': 'OK'}})

('cities_102', 'moorpark, CA', {'num_results': 1, 'error': None, 'data': {'results': [{'address_components': [{'long_name': 'Moorpark', 'short_name': 'Moorpark', 'types': ['locality', 'political']}, {'long_name': 'Ventura County', 'short_name': 'Ventura County', 'types': ['administrative_area_level_2', 'political']}, {'long_name': 'California', 'short_name': 'CA', 'types': ['administrative_area_level_1', 'political']}, {'long_name': 'United States', 'short_name': 'US', 'types': ['country', 'political']}, {'long_name': '93021', 'short_name': '93021', 'types': ['postal_code']}], 'formatted_address': 'Moorpark, CA 93021, USA', 'geometry': {'bounds': {'northeast': {'lat': 34.3079099, 'lng': -118.819801}, 'southwest': {'lat': 34.26074699999999, 'lng': -118.920523}}, 'location': {'lat': 34.285558, 'lng': -118.8820414}, 'location_type': 'APPROXIMATE', 'viewport': {'northeast': {'lat': 34.3079099, 'lng': -118.819801}, 'southwest': {'lat': 34.26074699999999, 'lng': -118.920523}}}, 'place_id': 'ChIJ7X5H3AQy6IARI7lFDpnB_7A', 'types': ['locality', 'political']}], 'status': 'OK'}})

('cities_103', 'ojai, CA', {'num_results': 1, 'error': None, 'data': {'results': [{'address_components': [{'long_name': 'Ojai', 'short_name': 'Ojai', 'types': ['locality', 'political']}, {'long_name': 'Ventura County', 'short_name': 'Ventura County', 'types': ['administrative_area_level_2', 'political']}, {'long_name': 'California', 'short_name': 'CA', 'types': ['administrative_area_level_1', 'political']}, {'long_name': 'United States', 'short_name': 'US', 'types': ['country', 'political']}, {'long_name': '93023', 'short_name': '93023', 'types': ['postal_code']}], 'formatted_address': 'Ojai, CA 93023, USA', 'geometry': {'bounds': {'northeast': {'lat': 34.470662, 'lng': -119.2204801}, 'southwest': {'lat': 34.429244, 'lng': -119.2745691}}, 'location': {'lat': 34.4480495, 'lng': -119.242889}, 'location_type': 'APPROXIMATE', 'viewport': {'northeast': {'lat': 34.470662, 'lng': -119.2204801}, 'southwest': {'lat': 34.429244, 'lng': -119.2745691}}}, 'place_id': 'ChIJe5jVXh646YARXyW-mTcvQWQ', 'types': ['locality', 'political']}], 'status': 'OK'}})

('cities_104', 'santa paula, CA', {'num_results': 1, 'error': None, 'data': {'results': [{'address_components': [{'long_name': 'Santa Paula', 'short_name': 'Santa Paula', 'types': ['locality', 'political']}, {'long_name': 'Ventura County', 'short_name': 'Ventura County', 'types': ['administrative_area_level_2', 'political']}, {'long_name': 'California', 'short_name': 'CA', 'types': ['administrative_area_level_1', 'political']}, {'long_name': 'United States', 'short_name': 'US', 'types': ['country', 'political']}, {'long_name': '93060', 'short_name': '93060', 'types': ['postal_code']}], 'formatted_address': 'Santa Paula, CA 93060, USA', 'geometry': {'bounds': {'northeast': {'lat': 34.383637, 'lng': -119.0353829}, 'southwest': {'lat': 34.326905, 'lng': -119.0970829}}, 'location': {'lat': 34.3541659, 'lng': -119.0592705}, 'location_type': 'APPROXIMATE', 'viewport': {'northeast': {'lat': 34.383637, 'lng': -119.0353829}, 'southwest': {'lat': 34.326905, 'lng': -119.0970829}}}, 'place_id': 'ChIJm0pej9W16YARIq9ZUPI4O-E', 'types': ['locality', 'political']}], 'status': 'OK'}})

('cities_105', 'simi valley, CA', {'num_results': 1, 'error': None, 'data': {'results': [{'address_components': [{'long_name': 'Simi Valley', 'short_name': 'Simi Valley', 'types': ['locality', 'political']}, {'long_name': 'Ventura County', 'short_name': 'Ventura County', 'types': ['administrative_area_level_2', 'political']}, {'long_name': 'California', 'short_name': 'CA', 'types': ['administrative_area_level_1', 'political']}, {'long_name': 'United States', 'short_name': 'US', 'types': ['country', 'political']}], 'formatted_address': 'Simi Valley, CA, USA', 'geometry': {'bounds': {'northeast': {'lat': 34.32265, 'lng': -118.632546}, 'southwest': {'lat': 34.208375, 'lng': -118.831115}}, 'location': {'lat': 34.2694474, 'lng': -118.781482}, 'location_type': 'APPROXIMATE', 'viewport': {'northeast': {'lat': 34.32265, 'lng': -118.632546}, 'southwest': {'lat': 34.208375, 'lng': -118.831115}}}, 'place_id': 'ChIJATNWW2wu6IARTUPTlI5Z4PQ', 'types': ['locality', 'political']}], 'status': 'OK'}})

('cities_106', 'thousand oaks, CA', {'num_results': 1, 'error': None, 'data': {'results': [{'address_components': [{'long_name': 'Thousand Oaks', 'short_name': 'Thousand Oaks', 'types': ['locality', 'political']}, {'long_name': 'Ventura County', 'short_name': 'Ventura County', 'types': ['administrative_area_level_2', 'political']}, {'long_name': 'California', 'short_name': 'CA', 'types': ['administrative_area_level_1', 'political']}, {'long_name': 'United States', 'short_name': 'US', 'types': ['country', 'political']}], 'formatted_address': 'Thousand Oaks, CA, USA', 'geometry': {'bounds': {'northeast': {'lat': 34.250779, 'lng': -118.7764739}, 'southwest': {'lat': 34.1247771, 'lng': -119.0016561}}, 'location': {'lat': 34.1761133, 'lng': -118.8487793}, 'location_type': 'APPROXIMATE', 'viewport': {'northeast': {'lat': 34.250779, 'lng': -118.7764739}, 'southwest': {'lat': 34.1247771, 'lng': -119.0016561}}}, 'navigation_points': [{'location': {'latitude': 34.1694461, 'longitude': -118.8358803}}], 'place_id': 'ChIJkYgocFYl6IARJi7MRwF6Lo0', 'types': ['locality', 'political']}], 'status': 'OK'}})

('cities_107', 'port hueneme, CA', {'num_results': 1, 'error': None, 'data': {'results': [{'address_components': [{'long_name': 'Port Hueneme', 'short_name': 'Port Hueneme', 'types': ['locality', 'political']}, {'long_name': 'Ventura County', 'short_name': 'Ventura County', 'types': ['administrative_area_level_2', 'political']}, {'long_name': 'California', 'short_name': 'CA', 'types': ['administrative_area_level_1', 'political']}, {'long_name': 'United States', 'short_name': 'US', 'types': ['country', 'political']}], 'formatted_address': 'Port Hueneme, CA, USA', 'geometry': {'bounds': {'northeast': {'lat': 34.1813119, 'lng': -119.186028}, 'southwest': {'lat': 34.137833, 'lng': -119.221454}}, 'location': {'lat': 34.1477829, 'lng': -119.1951074}, 'location_type': 'APPROXIMATE', 'viewport': {'northeast': {'lat': 34.1813119, 'lng': -119.186028}, 'southwest': {'lat': 34.137833, 'lng': -119.221454}}}, 'place_id': 'ChIJKcrafwBL6IARVHqFVcI6M0g', 'types': ['locality', 'political']}], 'status': 'OK'}})

## PROCESSING THE DATA WE GOT USING APIS

**Example Data**: 
<br>{'results': [{'address_components': [{'long_name': 'Agoura Hills', 'short_name': 'Agoura Hills', 'types': ['locality', 'political']},<br>
{'long_name': 'Los Angeles County', 'short_name': 'Los Angeles County', 'types': ['administrative_area_level_2', 'political']}, {'long_name': 'California', 'short_name': 'CA', 'types': ['administrative_area_level_1', 'political']}, {'long_name': 'United States', 'short_name': 'US', 'types': ['country', 'political']},<br> 
{'long_name': '91301', 'short_name': '91301', 'types': ['postal_code']}], 'formatted_address': 'Agoura Hills, CA 91301, USA',<br>
'geometry': {'bounds': {'northeast': {'lat': 34.168214, 'lng': -118.719776}, 'southwest': {'lat': 34.125329, 'lng': -118.8004199}}, 'location': {'lat': 34.1533395, 'lng': -118.7616764}, 'location_type': 'APPROXIMATE', 'viewport': {'northeast': {'lat': 34.168214, 'lng': -118.719776}, 'southwest': {'lat': 34.125329, 'lng': -118.8004199}}}, 'place_id': 'ChIJlRyqIx4h6IAR1v3fLa72Dqw', 'types': ['locality', 'political']}], 'status': 'OK'}

In [1]:
# Reading the 'api_locations' file that I have created using the API
import pandas as pd

api_locations = pd.read_csv('api_locations.csv', index_col=0)

# POST PROCESSING - important
# Making sure that the dictionaries in the dataframe are recognized by the python
import ast
# https://stackoverflow.com/questions/988228/convert-a-string-representation-of-a-dictionary-to-a-dictionary
# I have found this library from stackoverflow, which stated that 'as.literal_eval' as a safer alternative than just using 'eval' library.

print(isinstance(api_locations['raw_result'].iloc[0], dict))

# I need a double check for this because this gives an error when the code already is a dictionary.
if isinstance(api_locations['raw_result'].iloc[0], str):
    api_locations['raw_result'] = api_locations['raw_result'].apply(ast.literal_eval)

print(isinstance(api_locations['raw_result'].iloc[0], dict))
display(api_locations)

False
True

,geo_id,query,raw_result
0,cities_1,"agoura hills, CA","{'num_results': 1, 'error': None, 'data': {'re..."
1,cities_10,"carson, CA","{'num_results': 1, 'error': None, 'data': {'re..."
2,cities_100,"camarillo, CA","{'num_results': 1, 'error': None, 'data': {'re..."
3,cities_101,"fillmore, CA","{'num_results': 1, 'error': None, 'data': {'re..."
4,cities_102,"moorpark, CA","{'num_results': 1, 'error': None, 'data': {'re..."
...,...,...,...
477,neighborhoods_96,"calabasas, CA","{'num_results': 1, 'error': None, 'data': {'re..."
478,neighborhoods_97,"canoga park, CA","{'num_results': 1, 'error': None, 'data': {'re..."
479,neighborhoods_98,"carson, CA","{'num_results': 1, 'error': None, 'data': {'re..."
480,neighborhoods_99,"carthay, CA","{'num_results': 1, 'error': None, 'data': {'re..."
481,neighborhoods_178,"la caã±ada flintridge, CA","{'num_results': 1, 'error': None, 'data': {'re..."

In [3]:
# Creating a function that extracts the relevant information from the dictionary in 'raw result'
def extract_location_components(raw_result):
    try:
        first_result = raw_result['data']['results'][0] # Using the first capture
        components = first_result['address_components']
        geometry = first_result['geometry']['location']

        # Initialize output
        output = {
            "postal_code": None,
            "city": None,
            "county": None,
            "neighborhood": None,
            "lat": geometry.get('lat'),
            "lng": geometry.get('lng')
        }

        for comp in components:
            types = comp['types']
            if 'postal_code' in types:
                output['postal_code'] = comp['long_name']
            if 'locality' in types:
                output['city'] = comp['long_name']
            if 'administrative_area_level_2' in types:
                output['county'] = comp['long_name']
            if 'neighborhood' in types:
                output['neighborhood'] = comp['long_name']

        return output
    except:
        return {
            "postal_code": None,
            "city": None,
            "county": None,
            "neighborhood": None,
            "lat": None,
            "lng": None
        }

In [5]:
# Applying this function to every row to generate the 'location details' column
api_locations['location_details'] = api_locations['raw_result'].apply(extract_location_components)
display(api_locations)
# I do have 271 neighborhood information

,geo_id,query,raw_result,location_details
0,cities_1,"agoura hills, CA","{'num_results': 1, 'error': None, 'data': {'re...","{'postal_code': '91301', 'city': 'Agoura Hills..."
1,cities_10,"carson, CA","{'num_results': 1, 'error': None, 'data': {'re...","{'postal_code': None, 'city': 'Carson', 'count..."
2,cities_100,"camarillo, CA","{'num_results': 1, 'error': None, 'data': {'re...","{'postal_code': None, 'city': 'Camarillo', 'co..."
3,cities_101,"fillmore, CA","{'num_results': 1, 'error': None, 'data': {'re...","{'postal_code': '93015', 'city': 'Fillmore', '..."
4,cities_102,"moorpark, CA","{'num_results': 1, 'error': None, 'data': {'re...","{'postal_code': '93021', 'city': 'Moorpark', '..."
...,...,...,...,...
477,neighborhoods_96,"calabasas, CA","{'num_results': 1, 'error': None, 'data': {'re...","{'postal_code': None, 'city': 'Calabasas', 'co..."
478,neighborhoods_97,"canoga park, CA","{'num_results': 1, 'error': None, 'data': {'re...","{'postal_code': None, 'city': 'Los Angeles', '..."
479,neighborhoods_98,"carson, CA","{'num_results': 1, 'error': None, 'data': {'re...","{'postal_code': None, 'city': 'Carson', 'count..."
480,neighborhoods_99,"carthay, CA","{'num_results': 1, 'error': None, 'data': {'re...","{'postal_code': '90035', 'city': 'Los Angeles'..."
481,neighborhoods_178,"la caã±ada flintridge, CA","{'num_results': 1, 'error': None, 'data': {'re...","{'postal_code': '91011', 'city': 'La Cañada Fl..."

------------------------------------------------------------------------------------------------

In [8]:
# Expand the new informations in 'location_details' into new columns

location_df = pd.DataFrame(api_locations['location_details'].tolist())
#display(location_df)
api_locations_processed = pd.concat([api_locations, location_df], axis=1)

display(api_locations_processed)

,geo_id,query,raw_result,location_details,postal_code,city,county,neighborhood,lat,lng
0,cities_1,"agoura hills, CA","{'num_results': 1, 'error': None, 'data': {'re...","{'postal_code': '91301', 'city': 'Agoura Hills...",91301,Agoura Hills,Los Angeles County,None,34.153340,-118.761676
1,cities_10,"carson, CA","{'num_results': 1, 'error': None, 'data': {'re...","{'postal_code': None, 'city': 'Carson', 'count...",None,Carson,Los Angeles County,None,33.831674,-118.281693
2,cities_100,"camarillo, CA","{'num_results': 1, 'error': None, 'data': {'re...","{'postal_code': None, 'city': 'Camarillo', 'co...",None,Camarillo,Ventura County,None,34.216394,-119.037602
3,cities_101,"fillmore, CA","{'num_results': 1, 'error': None, 'data': {'re...","{'postal_code': '93015', 'city': 'Fillmore', '...",93015,Fillmore,Ventura County,None,34.399164,-118.918154
4,cities_102,"moorpark, CA","{'num_results': 1, 'error': None, 'data': {'re...","{'postal_code': '93021', 'city': 'Moorpark', '...",93021,Moorpark,Ventura County,None,34.285558,-118.882041
...,...,...,...,...,...,...,...,...,...,...
477,neighborhoods_96,"calabasas, CA","{'num_results': 1, 'error': None, 'data': {'re...","{'postal_code': None, 'city': 'Calabasas', 'co...",None,Calabasas,Los Angeles County,None,34.153973,-118.647380
478,neighborhoods_97,"canoga park, CA","{'num_results': 1, 'error': None, 'data': {'re...","{'postal_code': None, 'city': 'Los Angeles', '...",None,Los Angeles,Los Angeles County,Canoga Park,34.208309,-118.597532
479,neighborhoods_98,"carson, CA","{'num_results': 1, 'error': None, 'data': {'re...","{'postal_code': None, 'city': 'Carson', 'count...",None,Carson,Los Angeles County,None,33.831674,-118.281693
480,neighborhoods_99,"carthay, CA","{'num_results': 1, 'error': None, 'data': {'re...","{'postal_code': '90035', 'city': 'Los Angeles'...",90035,Los Angeles,Los Angeles County,Carthay Square,34.055838,-118.368030
481,neighborhoods_178,"la caã±ada flintridge, CA","{'num_results': 1, 'error': None, 'data': {'re...","{'postal_code': '91011', 'city': 'La Cañada Fl...",91011,La Cañada Flintridge,Los Angeles County,None,34.206818,-118.200028

In [10]:
# Read the 'api_locations_processed' dataframe
import csv
import pandas as pd

#api_loc_process = pd.read_csv('api_locations_processed.csv', dtype={'postal_code': str})
api_loc_process = api_locations_processed.copy()

# Dropping the index columns I don't need them
api_loc_process = api_loc_process.loc[:, ~api_loc_process.columns.str.startswith('Unnamed:')]

display(api_loc_process)

##################################################################################
#482 unique location combinations.

# 482x100x0.8 = 38560 house entries.
# Let's assume some will be duplicates and some will note be useful for me:
# I will have 30k houses for sure.

#38962 rows from the UCLA data, with extra columns derived using the API.
# 5,773 rows from usage_bld_kwh
# 23,089 rows from usage_vintage_kwh
# 2,406 usage_income_kwh.csv
# 6,735 rows from usage_sqft_kwh.csv
# 963 rows from geos.csv

# histogram of locations
# use the most occuring 150 locations.

,geo_id,query,raw_result,location_details,postal_code,city,county,neighborhood,lat,lng
0,cities_1,"agoura hills, CA","{'num_results': 1, 'error': None, 'data': {'re...","{'postal_code': '91301', 'city': 'Agoura Hills...",91301,Agoura Hills,Los Angeles County,None,34.153340,-118.761676
1,cities_10,"carson, CA","{'num_results': 1, 'error': None, 'data': {'re...","{'postal_code': None, 'city': 'Carson', 'count...",None,Carson,Los Angeles County,None,33.831674,-118.281693
2,cities_100,"camarillo, CA","{'num_results': 1, 'error': None, 'data': {'re...","{'postal_code': None, 'city': 'Camarillo', 'co...",None,Camarillo,Ventura County,None,34.216394,-119.037602
3,cities_101,"fillmore, CA","{'num_results': 1, 'error': None, 'data': {'re...","{'postal_code': '93015', 'city': 'Fillmore', '...",93015,Fillmore,Ventura County,None,34.399164,-118.918154
4,cities_102,"moorpark, CA","{'num_results': 1, 'error': None, 'data': {'re...","{'postal_code': '93021', 'city': 'Moorpark', '...",93021,Moorpark,Ventura County,None,34.285558,-118.882041
...,...,...,...,...,...,...,...,...,...,...
477,neighborhoods_96,"calabasas, CA","{'num_results': 1, 'error': None, 'data': {'re...","{'postal_code': None, 'city': 'Calabasas', 'co...",None,Calabasas,Los Angeles County,None,34.153973,-118.647380
478,neighborhoods_97,"canoga park, CA","{'num_results': 1, 'error': None, 'data': {'re...","{'postal_code': None, 'city': 'Los Angeles', '...",None,Los Angeles,Los Angeles County,Canoga Park,34.208309,-118.597532
479,neighborhoods_98,"carson, CA","{'num_results': 1, 'error': None, 'data': {'re...","{'postal_code': None, 'city': 'Carson', 'count...",None,Carson,Los Angeles County,None,33.831674,-118.281693
480,neighborhoods_99,"carthay, CA","{'num_results': 1, 'error': None, 'data': {'re...","{'postal_code': '90035', 'city': 'Los Angeles'...",90035,Los Angeles,Los Angeles County,Carthay Square,34.055838,-118.368030
481,neighborhoods_178,"la caã±ada flintridge, CA","{'num_results': 1, 'error': None, 'data': {'re...","{'postal_code': '91011', 'city': 'La Cañada Fl...",91011,La Cañada Flintridge,Los Angeles County,None,34.206818,-118.200028

In [14]:
# Next step is to properly merge the 'api_loc_process' with the 'ucla_merged.csv' file.

import pandas as pd

# Load data
ucla_df = pd.read_csv('ucla_merged.csv')
api_df = api_loc_process.copy()

# Merge on geo_id (left join to preserve all ucla_df rows)
merged_df = pd.merge(ucla_df, api_df, on='geo_id', how='left', suffixes=('', '_api'))

# Keep only rows where 'name' is found in 'query' (or query is NaN so that ucla rows are retained)
merged_df = merged_df[merged_df['query'].isna() | merged_df.apply(lambda row: row['name'] in row['query'], axis=1)]

# Drop extra index columns if present
merged_df = merged_df.loc[:, ~merged_df.columns.str.startswith('Unnamed:')]

# Save the file with every row
##merged_df.to_csv('ucla_merged_with_api.csv', index=False)

# Save the final deliverable with trimming unnecessdary columns out.
columns_to_keep = ['geo_id','sqft','usage','usage_med','usage_med_sqft','usetype',
                   'year','name','solar_potential','pop','usage_percap','source',
                   'vintage_id','income_quintile','income_range','sqft_id','pop_sqmi',
                   'med_income','pct_own','pct_rent','enviroscreen_tracts','sqmi',
                  'solar_pot','net_solar_pot','count','query','postal_code','city','county','neighborhood','lat','lng']

final_df_col = merged_df[columns_to_keep]

# Save the final file
final_df_col.to_csv('ucla_final.csv', index=False)

# Saving the final file into Craigslist_Scraping
final_df_col.to_csv('../Craigslist_Scraping/ucla_final.csv', index=False)

# Saving the final file into Predicting_Energy
final_df_col.to_csv('../Predicting_Energy/ucla_final.csv', index=False)

/var/folders/w_/_pjdhc9x5pndg2r8dn0lh6h00000gn/T/ipykernel_39718/3295976022.py:6: DtypeWarning: Columns (11,15) have mixed types. Specify dtype option on import or set low_memory=False.
  ucla_df = pd.read_csv('ucla_merged.csv')